import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { schemaText } from '../xml-input.js';
import type { Request, Observation } from '../primary-worker.ts';
import { isolated } from '../primary.js';
import { captureProvenance, finishProvenance, fixtureInputs, referenceSources } from './provenance.js';
const root = resolve(process.argv[2] ?? 'tmp/conformance/node-qualification');
const execution = captureProvenance(referenceSources(), fixtureInputs(),
    ['package.json', 'lib/index.mjs', 'lib/libxml2raw.mjs'].map(path => resolve(root, 'node_modules/libxml2-wasm', path)));
const xsd = '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="root" type="xs:int"/></xs:schema>';
const base: Request = { candidateRoot: root, schema: xsd, uri: 'fixture:///main.xsd', instances: ['<root>1</root>', '<root>x</root>'], resources: {} };
const observations: Record<string, Observation> = {};
observations.positiveNegative = await isolated(base);
assert.equal(observations.positiveNegative.outcome, 'accepted');
assert.deepEqual(observations.positiveNegative.instances?.map(i => i.outcome), ['accepted', 'rejected']);
observations.repeatedDisposal = await isolated({ ...base, iterations: 100 });
assert.deepEqual(observations.repeatedDisposal.undisposed, {});
const inherited = '<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:qualified"><w:types><x:schema targetNamespace="urn:qualified"><x:complexType name="T"/><x:element name="root" type="t:T"/></x:schema></w:types></w:definitions>';
assert.match(schemaText(inherited), /xmlns:t="urn:qualified"/);
observations.namespaceInheritance = await isolated({ ...base, schema: inherited, instances: ['<root xmlns="urn:qualified"/>'] });
assert.equal(observations.namespaceInheritance.instances?.[0].outcome, 'accepted');
const composition = '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:include schemaLocation="a/same.xsd"/><xs:include schemaLocation="b/same.xsd"/></xs:schema>';
const element = (name: string) => `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="${name}" type="xs:int"/></xs:schema>`;
observations.localComposition = await isolated({ ...base, schema: composition, resources: { 'fixture:///a/same.xsd': element('a'), 'fixture:///b/same.xsd': element('b') }, instances: ['<a>1</a>', '<b>2</b>'] });
assert.deepEqual(observations.localComposition.instances?.map(i => i.outcome), ['accepted', 'accepted']);
observations.unknownResource = await isolated({ ...base, schema: composition });
assert.equal(observations.unknownResource.phase, 'input');
assert.match(observations.unknownResource.diagnostic!, /Unknown resource/);
observations.networkResource = await isolated({ ...base, schema: composition.replace('a/same.xsd', 'https://example.test/remote.xsd') });
assert.equal(observations.networkResource.phase, 'input');
observations.doctype = await isolated({ ...base, schema: '<!DOCTYPE xs:schema SYSTEM "https://example.test/a.dtd">' + xsd });
assert.equal(observations.doctype.phase, 'input');
assert.match(observations.doctype.diagnostic!, /DOCTYPE/);
observations.malformed = await isolated({ ...base, schema: '<xs:schema' });
assert.equal(observations.malformed.phase, 'input');
observations.malformedInstance = await isolated({ ...base, instances: ['<root>'] });
assert.equal(observations.malformedInstance.phase, 'input');
const fixture = readFileSync('test/conformance/fixtures/xsd/compositors/content-model-invalid-all.wsdl', 'utf8');
observations.invalidSchema = await isolated({ ...base, schema: fixture });
assert.equal(observations.invalidSchema.phase, 'schema');
assert.equal(observations.invalidSchema.outcome, 'rejected');
assert.equal(observations.invalidSchema.instances, undefined);
const exactBytes = Buffer.byteLength(xsd) + base.instances.reduce((n, s) => n + Buffer.byteLength(s), 0);
observations.bytesAt = await isolated({ ...base, maxBytes: exactBytes });
assert.equal(observations.bytesAt.outcome, 'accepted');
observations.bytesBeyond = await isolated({ ...base, maxBytes: exactBytes - 1 });
assert.equal(observations.bytesBeyond.outcome, 'resource-limit');
assert.equal(observations.bytesBeyond.instances, undefined);
observations.elapsedBeyond = await isolated({ ...base, iterations: 1000000000 }, 300);
assert.equal(observations.elapsedBeyond.outcome, 'resource-limit');
assert.equal(observations.elapsedBeyond.instances, undefined);
observations.pathEscape = await isolated({ ...base, uri: 'fixture:///../../outside.xsd' });
assert.equal(observations.pathEscape.phase, 'input');
observations.missingEngine = await isolated({ ...base, candidateRoot: resolve('tmp/conformance/missing-candidate') });
assert.equal(observations.missingEngine.phase, 'setup');
for (const [name, result] of Object.entries(observations))
    if (result.undisposed !== undefined)
        assert.deepEqual(result.undisposed, {}, name + ' leaked objects');
writeFileSync('tmp/conformance/node-qualification/primary-boundaries.json', JSON.stringify({ provenance: finishProvenance(execution), node: process.version, platform: process.platform, observations, limits: 'Worker JS heap limits do not cap WASM linear memory or total process RSS. Final platform qualification remains #253.' }, null, 2) + '\n');
console.log('Primary candidate boundary checks passed (15 cases; no platform matrix claim).');
