/**
 * Handler Implementation Examples
 *
 * This file demonstrates how to implement the stub handlers generated by the gateway tool
 * with actual SOAP client calls and proper error handling.
 *
 * There are several approaches:
 * 1. Modify the generated route files directly
 * 2. Create wrapper functions that override the handlers
 * 3. Use Fastify plugins to encapsulate handler logic
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
// import { WeatherClient } from '../../tmp/client.js';
// import type { GetCityWeatherByZIP, GetCityWeatherByZIPResponse } from '../../tmp/types.js';

/**
 * Standard Response Envelope (matches OpenAPI generator output)
 */
interface StandardEnvelope<T = any> {
  status: 'SUCCESS' | 'FAILURE' | 'PENDING';
  message: string | null;
  data: T | null;
  error: {
    code: string;
    message: string;
    details: any;
  } | null;
}

/**
 * Example 1: Simple handler implementation
 *
 * Replace the stub handler in the generated route file with this implementation.
 */
export async function getCityWeatherByZIPHandler(
  request: FastifyRequest,
  reply: FastifyReply
): Promise<StandardEnvelope> {
  try {
    // 1. Extract validated request body
    // (Fastify has already validated it against the schema)
    const input = request.body as any; // Use proper type: GetCityWeatherByZIP

    // 2. Call the SOAP service
    // const client = new WeatherClient('http://wsf.cdyne.com/WeatherWS/Weather.asmx');
    // const result = await client.GetCityWeatherByZIP(input);

    // 3. Mock response for demonstration
    const result = {
      Success: true,
      ResponseText: 'Weather data retrieved',
      State: 'CA',
      City: 'Beverly Hills',
      WeatherStationCity: 'Los Angeles',
      WeatherID: 1,
      Description: 'Sunny',
      Temperature: '72',
      RelativeHumidity: '45',
      Wind: 'NW 5 mph',
      Pressure: '30.12 in',
      Visibility: '10 mi',
      WindChill: '',
      Remarks: ''
    };

    // 4. Return in standard envelope format
    return {
      status: 'SUCCESS',
      message: null,
      data: result,
      error: null,
    };
  } catch (error: any) {
    // 5. Handle errors gracefully
    request.log.error(error, 'SOAP call failed');

    // Return error in envelope format
    reply.code(500);
    return {
      status: 'FAILURE',
      message: 'Failed to retrieve weather data',
      data: null,
      error: {
        code: 'SOAP_ERROR',
        message: error.message || 'Unknown error',
        details: process.env.NODE_ENV === 'development' ? error.stack : null,
      },
    };
  }
}

/**
 * Example 2: Handler with input validation and business logic
 */
export async function getCityForecastByZIPHandler(
  request: FastifyRequest,
  reply: FastifyReply
): Promise<StandardEnvelope> {
  const input = request.body as any; // GetCityForecastByZIP

  try {
    // Additional business logic validation
    if (input.ZIP && !/^\d{5}$/.test(input.ZIP)) {
      reply.code(400);
      return {
        status: 'FAILURE',
        message: 'Invalid ZIP code format',
        data: null,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'ZIP code must be 5 digits',
          details: { field: 'ZIP', value: input.ZIP },
        },
      };
    }

    // Call SOAP service
    // const client = new WeatherClient('http://wsf.cdyne.com/WeatherWS/Weather.asmx');
    // const result = await client.GetCityForecastByZIP(input);

    // Mock response
    const result = {
      Success: true,
      ResponseText: 'Forecast retrieved',
      State: 'CA',
      City: 'Beverly Hills',
      WeatherStationCity: 'Los Angeles',
      ForecastResult: [
        {
          Date: new Date().toISOString(),
          WeatherID: 1,
          Desciption: 'Sunny',
          Temperatures: { MorningLow: '60', DaytimeHigh: '75' },
          ProbabilityOfPrecipiation: { Nighttime: '0%', Daytime: '10%' },
        },
      ],
    };

    return {
      status: 'SUCCESS',
      message: null,
      data: result,
      error: null,
    };
  } catch (error: any) {
    request.log.error(error, 'Failed to get forecast');

    // Map different error types to appropriate HTTP status codes
    const statusCode = error.statusCode || 500;
    reply.code(statusCode);

    return {
      status: 'FAILURE',
      message: 'Failed to retrieve forecast',
      data: null,
      error: {
        code: error.code || 'SOAP_ERROR',
        message: error.message,
        details: process.env.NODE_ENV === 'development' ? error : null,
      },
    };
  }
}

/**
 * Example 3: Factory function to create handlers with dependency injection
 */
export function createWeatherHandlers(soapServiceUrl: string) {
  // const client = new WeatherClient(soapServiceUrl);

  return {
    getCityWeatherByZIP: async (request: FastifyRequest, reply: FastifyReply) => {
      const input = request.body as any;

      try {
        // const result = await client.GetCityWeatherByZIP(input);
        const result = { Success: true, /* mock data */ };

        return {
          status: 'SUCCESS',
          message: null,
          data: result,
          error: null,
        };
      } catch (error: any) {
        reply.code(500);
        return {
          status: 'FAILURE',
          message: 'SOAP service error',
          data: null,
          error: {
            code: 'SOAP_ERROR',
            message: error.message,
            details: null,
          },
        };
      }
    },

    getCityForecastByZIP: async (request: FastifyRequest, reply: FastifyReply) => {
      const input = request.body as any;

      try {
        // const result = await client.GetCityForecastByZIP(input);
        const result = { Success: true, /* mock data */ };

        return {
          status: 'SUCCESS',
          message: null,
          data: result,
          error: null,
        };
      } catch (error: any) {
        reply.code(500);
        return {
          status: 'FAILURE',
          message: 'SOAP service error',
          data: null,
          error: {
            code: 'SOAP_ERROR',
            message: error.message,
            details: null,
          },
        };
      }
    },
  };
}

/**
 * Example 4: Fastify plugin approach
 *
 * This encapsulates all handlers and dependencies in a reusable plugin.
 */
export async function weatherHandlersPlugin(
  fastify: FastifyInstance,
  options: { soapServiceUrl: string }
) {
  // const client = new WeatherClient(options.soapServiceUrl);

  // Decorate fastify with the SOAP client
  fastify.decorate('soapClient', /* client */ {});

  // Override the stub handlers
  // You would need to remove the generated route registration and add your own:

  fastify.post('/get-city-weather-by-zip', {
    schema: {}, // Import from generated operation schema
    handler: async (request, reply) => {
      const input = request.body as any;

      try {
        // const result = await fastify.soapClient.GetCityWeatherByZIP(input);
        const result = { Success: true };

        return {
          status: 'SUCCESS',
          message: null,
          data: result,
          error: null,
        };
      } catch (error: any) {
        reply.code(500);
        return {
          status: 'FAILURE',
          message: 'Service error',
          data: null,
          error: {
            code: 'SOAP_ERROR',
            message: error.message,
            details: null,
          },
        };
      }
    },
  });
}

/**
 * Example 5: Error mapping utility
 *
 * Maps SOAP errors to appropriate HTTP status codes and error responses.
 */
export class ErrorMapper {
  static mapSoapError(error: any): { statusCode: number; envelope: StandardEnvelope } {
    // Map SOAP fault codes to HTTP status codes
    const statusCodeMap: Record<string, number> = {
      'soap:Client': 400,
      'soap:Server': 500,
      'soap:MustUnderstand': 400,
      'soap:VersionMismatch': 400,
    };

    const statusCode = statusCodeMap[error.faultcode] || 500;

    return {
      statusCode,
      envelope: {
        status: 'FAILURE',
        message: 'SOAP service error',
        data: null,
        error: {
          code: error.faultcode || 'SOAP_ERROR',
          message: error.faultstring || error.message,
          details: {
            faultcode: error.faultcode,
            faultstring: error.faultstring,
            detail: error.detail,
          },
        },
      },
    };
  }

  static createSuccessEnvelope<T>(data: T): StandardEnvelope<T> {
    return {
      status: 'SUCCESS',
      message: null,
      data,
      error: null,
    };
  }
}

/**
 * Usage example:
 *
 * 1. Direct replacement in generated route file:
 *    Edit tmp/gateway/routes/getcityweatherbyzip.ts
 *    Replace the handler with: handler: getCityWeatherByZIPHandler
 *
 * 2. Factory approach:
 *    const handlers = createWeatherHandlers('http://soap-url');
 *    // Use handlers in your own route registration
 *
 * 3. Plugin approach:
 *    fastify.register(weatherHandlersPlugin, { soapServiceUrl: 'http://soap-url' });
 *
 * Note: Generated route functions now use the naming pattern:
 *   registerRoute_{version}_{service}_{operation}
 *   Example: registerRoute_v1_weather_getcityweatherbyzip
 */

