<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:re01:au"
           targetNamespace="urn:re01:au">
  <xs:attribute name="g" type="xs:int"/>
  <xs:complexType name="A">
    <xs:sequence><xs:element name="a" type="xs:string" minOccurs="0"/></xs:sequence>
    <xs:attribute ref="t:g" fixed="1"/>
  </xs:complexType>
  <xs:complexType name="E">
    <xs:complexContent>
      <xs:extension base="t:A">
        <xs:sequence>
          <xs:choice/>
          <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
        <xs:attribute ref="t:g" fixed="2"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="D">
    <xs:complexContent>
      <xs:restriction base="t:E">
        <xs:sequence><xs:element name="a" type="xs:int"/></xs:sequence>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="root" type="t:D"/>
</xs:schema>
