import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { findExampleDrift } from "../../scripts/lib/preflight-examples.mjs";

const tempRoots: string[] = [];

async function createFixtureRoot(name: string): Promise<string> {
  const root = path.resolve("tmp", `preflight-examples-${name}`);
  await rm(root, { force: true, recursive: true });
  await mkdir(root, { recursive: true });
  tempRoots.push(root);
  return root;
}

async function writeFixture(root: string, relativePath: string, content: string): Promise<void> {
  const filePath = path.join(root, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

function catalogJson(wsdl: string, out: string): string {
  return `${JSON.stringify(
    {
      options: {
        wsdl,
        out,
        imports: "js",
      },
      wsdlUri: wsdl,
      serviceName: "Weather",
    },
    null,
    2
  )}\n`;
}

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { force: true, recursive: true })));
});

describe("findExampleDrift", () => {
  it("ignores committed README files that are not regenerated by the pipeline", async () => {
    const left = await createFixtureRoot("readme-left");
    const right = await createFixtureRoot("readme-right");
    await writeFixture(left, "README.md", "# Generated Output Example\n");

    expect(findExampleDrift(left, right, { root: path.resolve(".") })).toEqual([]);
  });

  it("normalizes catalog paths that vary by regeneration directory", async () => {
    const repoRoot = path.resolve(".");
    const left = await createFixtureRoot("catalog-left");
    const right = await createFixtureRoot("catalog-right");
    await writeFixture(
      left,
      "client/catalog.json",
      catalogJson("examples/minimal/weather.wsdl", path.join(repoRoot, "examples", "generated-output", "client"))
    );
    await writeFixture(
      right,
      "client/catalog.json",
      catalogJson(path.join(repoRoot, "examples", "minimal", "weather.wsdl"), path.join(repoRoot, "tmp", "preflight-examples", "client"))
    );

    expect(findExampleDrift(left, right, { root: repoRoot })).toEqual([]);
  });

  it("reports actual generated file drift", async () => {
    const left = await createFixtureRoot("drift-left");
    const right = await createFixtureRoot("drift-right");
    await writeFixture(left, "gateway/plugin.ts", "export const value = 1;\n");
    await writeFixture(right, "gateway/plugin.ts", "export const value = 2;\n");

    expect(findExampleDrift(left, right, { root: path.resolve(".") })).toEqual(["gateway/plugin.ts"]);
  });
});
